/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_yushan_HelloWorld */

#ifndef _Included_io_yushan_HelloWorld
#define _Included_io_yushan_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_yushan_HelloWorld
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_yushan_HelloWorld_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     io_yushan_HelloWorld
 * Method:    readBytes
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_yushan_HelloWorld_readBytes
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
